# Generated by Django 3.1.1 on 2020-12-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_answer_answer_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('question_num', models.IntegerField()),
                ('text', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('text_question', 'text_question'), ('choice_question', 'choice_question')], max_length=16)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.task')),
            ],
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='task',
        ),
        migrations.DeleteModel(
            name='TextQuestion',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='backend.question'),
        ),
        migrations.DeleteModel(
            name='ChoiceQuestion',
        ),
    ]
