# Generated by Django 3.1.1 on 2020-12-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201206_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_num',
        ),
    ]
