# Generated by Django 3.1.1 on 2021-01-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_num', models.IntegerField()),
                ('text', models.CharField(max_length=64)),
                ('is_true', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('textQuestion', 'textQuestion'), ('choiceQuestion', 'choiceQuestion')], max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='ChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='TextQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.question'),
        ),
    ]
