# Generated by Django 3.1.1 on 2020-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='check_on_submit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
