# Generated by Django 3.1.1 on 2021-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orderattemptanswer',
            name='value',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='textchoiceattemptanswer',
            name='value',
            field=models.CharField(max_length=256),
        ),
    ]
