# Generated by Django 3.1.1 on 2021-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled', max_length=64),
            preserve_default=False,
        ),
    ]
