# Generated by Django 3.1.1 on 2021-04-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='answer',
            field=models.CharField(default='dsa', max_length=64),
            preserve_default=False,
        ),
    ]
