# Generated by Django 3.1.1 on 2021-01-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210108_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='Untitled', max_length=32),
            preserve_default=False,
        ),
    ]
