# Generated by Django 3.1.1 on 2020-09-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_check_on_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='answer',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, null=True)),
                ('text', models.TextField()),
                ('choices', models.TextField()),
                ('answer', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
