# Generated by Django 3.1.1 on 2021-07-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210709_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderattemptanswer',
            name='value',
            field=models.TextField(),
        ),
    ]
