# Generated by Django 3.1.1 on 2020-09-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200920_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
